// <auto-generated />
using System;
using BTCPayServer.Plugins.RGB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BTCPayServer.Plugins.RGB.Migrations
{
    [DbContext(typeof(RGBPluginDbContext))]
    [Migration("20260107192353_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BTCPayServer.Plugins.RGB.Data.Entities.RGBAsset", b =>
                {
                    b.Property<string>("AssetId")
                        .HasColumnType("text");

                    b.Property<bool>("AcceptForPayment")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<long>("IssuedSupply")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Precision")
                        .HasColumnType("integer");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WalletId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AssetId");

                    b.HasIndex("WalletId");

                    b.ToTable("RGB_Assets", (string)null);
                });

            modelBuilder.Entity("BTCPayServer.Plugins.RGB.Data.Entities.RGBInvoice", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<long?>("Amount")
                        .HasColumnType("bigint");

                    b.Property<string>("AssetId")
                        .HasColumnType("text");

                    b.Property<int?>("BatchTransferIdx")
                        .HasColumnType("integer");

                    b.Property<string>("BtcPayInvoiceId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("ExpirationTimestamp")
                        .HasColumnType("bigint");

                    b.Property<string>("Invoice")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsBlind")
                        .HasColumnType("boolean");

                    b.Property<long?>("ReceivedAmount")
                        .HasColumnType("bigint");

                    b.Property<string>("RecipientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("SettledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Txid")
                        .HasColumnType("text");

                    b.Property<string>("WalletId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BtcPayInvoiceId");

                    b.HasIndex("RecipientId");

                    b.HasIndex("Status");

                    b.HasIndex("WalletId");

                    b.ToTable("RGB_Invoices", (string)null);
                });

            modelBuilder.Entity("BTCPayServer.Plugins.RGB.Data.Entities.RGBWallet", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncryptedMnemonic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MasterFingerprint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Network")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StoreId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("XpubColored")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("XpubVanilla")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("RGB_Wallets", (string)null);
                });

            modelBuilder.Entity("BTCPayServer.Plugins.RGB.Data.Entities.RGBAsset", b =>
                {
                    b.HasOne("BTCPayServer.Plugins.RGB.Data.Entities.RGBWallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("BTCPayServer.Plugins.RGB.Data.Entities.RGBInvoice", b =>
                {
                    b.HasOne("BTCPayServer.Plugins.RGB.Data.Entities.RGBWallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });
#pragma warning restore 612, 618
        }
    }
}
